#配置tomcat的端口
server:
  port: 8082
  servlet:
    context-path: /

#配置数据库的数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.241.132:3306/db_ebusiness?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid: #配置 Druid 的相关参数
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      min-evictable-idle-time-millis: 300000   # 配置一个连接在池中最小生存时间
      validation-query: SELECT 1              #SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true  # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      max-pool-prepared-statement-per-connection-size: 20
      #filters: stat,wall,log4j  # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      web-stat-filter: # 配置 DruidStatFilter
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      stat-view-servlet: # 配置 DruidStatViewServlet
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123456
  #配置视图的前缀和后缀
  mvc:
    view:
      prefix: /templates/   #前缀
      suffix: .html       #后缀
    static-path-pattern: /**   #配置静态资源的访问路径
  web:
    resources:
      static-locations: classpath:/static  #静态资源的映射路径



#配置MyBatis-plus
mybatis-plus:
  type-aliases-package: com.lyj.entity #配置类的别名
  mapper-locations: classpath:mappers/*.xml  #sql映射文件的位置
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射

saveImage: #设置文件上传的路径
  path: D:\software\IntelliJ IDEA 2020.3.1\MyWorks2\MySelfStudy\ebusiness\src\main\resources\static\images\
